#
# Copyright (c) 2019-2020 BedRock Systems, Inc.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

# Coqdoc settings.
# Presupposes $(ROOT) points to the repository root.

EXTRA_DIR=$(ROOT)/coqdocjs/extra
COQDOCFLAGS:= \
  --toc --toc-depth 2 --html --interpolate \
  --index indexpage --no-lib-name --parse-comments \
  --external https://plv.mpi-sws.org/coqdoc/iris/ iris \
  --external https://plv.mpi-sws.org/coqdoc/stdpp/ stdpp \
  --with-header $(EXTRA_DIR)/header.html --with-footer $(EXTRA_DIR)/footer.html
export COQDOCFLAGS
