#!/bin/sh
#
# Copyright (C) BedRock Systems Inc. 2020-2023
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

target=dune.inc

usage() {
	cat >&2 <<-EOF
		usage: $(basename "$0")

		This will invoke ./cpp2v-dune-gen.sh for every C or C++ file under
		the current directory, sending the dune rules to ${target}.
	EOF
        exit 1
}

[ $# = 0 ] || usage

exec > ${target}

echo "; DO NOT EDIT: Generated by \"$0${1+ $*}\""

# Cross-language tests
for file in valcat_of.cpp
do
	for std in 11 14 17 20
	do
		base="${file%.*}"
		ext="${file##*.}"
		tu="${base}_${std}_${ext}.v"
		cat <<-EOF
			(rule
			 (targets ${tu})
			 (deps (:input ${file}))
			 (action
			  (run cpp2v -v %{input} -o ${tu} -- -std=c++${std})))
		EOF
	done
done

find . -name '*.[ch]pp' | sort | while read i; do ./cpp2v-dune-gen.sh -- $i -- -std=c++17; done
find . -name '*.[ch]'  | sort | while read i; do ./cpp2v-dune-gen.sh -- $i -- -std=c99; done
