#
# Copyright (C) BedRock Systems Inc. 2019 Gregory Malecha
#
# SPDX-License-Identifier:AGPL-3.0-or-later
#
CS=$(wildcard *.c)
HS=$(wildcard *.h)
CPPS=$(wildcard *.cpp)
HPPS=$(wildcard *.hpp)
CPP2V?=$(shell which cpp2v)

VS=$(patsubst %.h,%_h.v,$(HS)) $(patsubst %.hpp,%_hpp.v,$(HPPS)) $(patsubst %.c,%_c.v,$(CS)) $(patsubst %.cpp,%_cpp.v,$(CPPS))
VOS=$(patsubst %.v,%.vo,$(VS))

CFLAGS=

coq: Makefile.coq $(VS)
	$(MAKE) -f Makefile.coq

clean:
	@ rm $(VS) -rf $(VOS)

%_c.v: %.c $(CPP2V)
	$(CPP2V) $< -- $(CFLAGS) > $@
%_h.v: %.h $(CPP2V)
	$(CPP2V) $< -- $(CFLAGS) > $@
%_cpp.v: %.cpp $(CPP2V)
	$(CPP2V) $< -- $(CFLAGS) > $@
%_hpp.v: %.hpp $(CPP2V)
	$(CPP2V) $< -- $(CFLAGS) > $@

%.o: %.cpp
	gcc -c $<

Makefile.coq: $(VS)
	coq_makefile -f _CoqProject -o Makefile.coq
