CS=$(wildcard *.c)
HS=$(wildcard *.h)
CPPS=$(wildcard *.cpp)
HPPS=$(wildcard *.hpp)

VS=$(patsubst %.h,%_h.v,$(HS)) $(patsubst %.hpp,%_hpp.v,$(HPPS)) $(patsubst %.c,%_c.v,$(CS)) $(patsubst %.cpp,%_cpp.v,$(CPPS))
VOS=$(patsubst %.v,%.vo,$(VS))

CFLAGS=

coq: Makefile.coq $(VS)
	$(MAKE) -f Makefile.coq

clean:
	@ rm $(VS) $(VOS)

%_c.v: %.c
	./../cpp2v $< -- $(CFLAGS) > $@
%_h.v: %.h
	./../cpp2v $< -- $(CFLAGS) > $@
%_cpp.v: %.cpp
	./../cpp2v $< -- $(CFLAGS) > $@
%_hpp.v: %.hpp
	./../cpp2v $< -- $(CFLAGS) > $@

%.o: %.cpp
	gcc -c $<

Makefile.coq: $(VS)
	coq_makefile -f _CoqProject -o Makefile.coq
