#
# Copyright (C) BedRock Systems Inc. 2019 Gregory Malecha
#
# SPDX-License-Identifier: LGPL-2.1 WITH BedRock Exception for use over network, see repository root for details.
#

DIRS=

all: $(DIRS)

$(DIRS):
	$(MAKE) -C $@

.PHONY: $(DIRS)

clean:
	$(foreach d,$(DIRS), $(MAKE) -C $(d) clean;)