#
# Copyright (c) 2019 BedRock Systems, Inc.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

DIRS=

all: $(DIRS)

$(DIRS):
	$(MAKE) -C $@

.PHONY: $(DIRS)

clean:
	$(foreach d,$(DIRS), $(MAKE) -C $(d) clean;)