#!/usr/bin/awk -f
#
# Copyright (C) BedRock Systems Inc. 2024
# All rights reserved.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.

# Usage: sha512sum file ... | ./dummy-gen.awk
# Example: ../cpp2v-core/theories/prelude/dune

function quote(s) {
	gsub(/"/, "\"\"", s);
	return sprintf("\"%s\"", s);
}

BEGIN{
	printf("(* DO NOT EDIT: Generated by dune *)\n\n");
	printf("Require Import bedrock.prelude.bytestring.\n\n");
	printf("#[local] Open Scope bs_scope.\n\n");
	printf("Definition deps : list (bs * bs) :=\n");
}

{
	if (NF == 2)
		printf("  (%s, %s) ::\n", quote($1), quote($2));
	else
		errors = 1;
}

END{
	printf("  nil.\n");
	if (errors) {
		printf("dummy-gen.awk: Warning: Some input lines were malformed, and omitted\n") >> "/dev/stderr"
	}
	exit errors
}
