(lang dune 3.6)
(using coq 0.6)
(name coq-lens)

(generate_opam_files)

(maintainers
 "Gregory Malecha <gregory@bedrocksystems.com>")
(authors
 "Gregory Malecha <gregory@bedrocksystems.com>")
(source (github bedrocksystems/cpp2v))

(package
 (name coq-lens)
 (synopsis "Generation of lenses for record datatypes")
 (depends
  (coq (and (>= 8.13.0) (< 8.19~)))))

(package
 (name coq-lens-tc)
 (synopsis "Generation of lenses for record datatypes")
 (depends
  coq-lens
  (coq (and (>= 8.17.0) (< 8.18~)))
  (coq-metacoq-template (= 1.2+8.17))))

(package
 (name coq-lens-elpi)
 (synopsis "Generation of lenses for record datatypes, Elpi backend")
 (depends
  coq-lens
  coq-elpi))
